---
apiVersion: kubeflow.org/v1alpha1
kind: Notebook
metadata:
  name: notebook-sample-v1alpha1
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: apoger/jupyter:v1.6.0-rc.0
