name: Build & Publish CentralDashboard Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard/**
    types:
      - closed 

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run CentralDashboard build
      run: |
        cd components/centraldashboard
        export IMG=kubeflownotebookswg/centraldashboard
        make docker-build

    - name: Run CentralDashboard push
      run: |
        cd components/centraldashboard
        export IMG=kubeflownotebookswg/centraldashboard
        make docker-push
