name: Build & Publish CentralDashboard-Angular Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard-angular/**
      - releasing/version/VERSION

env:
  DOCKER_USER: apoger
  IMG: apoger/centraldashboard-angular
  TAG: latest

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Run CentralDashboard-Angular build
      run: |
        cd components/centraldashboard-angular
        make docker-build

    - name: Run CentralDashboard-Angular push
      run: |
        cd components/centraldashboard-angular
        make docker-push

    - name: Run CentralDashboard-Angular push on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export VERSION_TAG=$(cat releasing/version/VERSION)
        docker tag ${{env.IMG}}:${{env.TAG}} ${{env.IMG}}:${VERSION_TAG}
        docker push ${{env.IMG}}:${VERSION_TAG}
