name: Build CentralDashboard-Angular Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard-angular/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/centraldashboard-angular
  TAG: top-level-latest

jobs:
  push_to_registry:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Run CentralDashboard-Angular build
      run: |
        cd components/centraldashboard-angular
        make docker-build

    - name: Run CentralDashboard build on version tag
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/centraldashboard-angular
        make docker-build
