name: Build Notebook Controller Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/notebook-controller
  ARCH: linux/ppc64le,linux/amd64
  TAG: top-level-latest

jobs:
  push_to_registry:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ppc64le

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi-arch docker image
      run: |
        cd components/notebook-controller
        make docker-build-multi-arch

    - name: Build multi-arch docker image on Version change
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/notebook-controller
        make docker-build-multi-arch
