name: Build Jupyter SciPy Notebook Server Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-scipy/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  TAG: top-level-latest
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build -C jupyter-scipy TAG=${{env.TAG}}
    
    - name: Push Notebook Server images
      run: |
        docker tag jupyter-scipy:${{env.TAG}} ${{env.REGISTRY}}/jupyter-scipy:${{env.TAG}}

    - name: Push Notebook Server images on Version change
      run: |
        export VERSION_TAG=$(cat releasing/version/VERSION)
        echo ${VERSION_TAG}
        docker tag jupyter-scipy:${{env.TAG}} ${{env.REGISTRY}}/jupyter-scipy:${VERSION_TAG}
