name: Build Jupyter TensorFlow Full Notebook Server Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-tensorflow-full/**
      - components/example-notebook-servers/jupyter-tensorflow/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  TAG: top-level-latest
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-tensorflow-full TAG=${{env.TAG}}
        make docker-build-cuda -C jupyter-tensorflow-full TAG=${{env.TAG}}
    
    - name: Push Notebook Server images
      run: |
        docker tag jupyter-tensorflow-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-full:${{env.TAG}}
        docker tag jupyter-tensorflow-cuda-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-cuda-full:${{env.TAG}}

    - name: Push Notebook Server images on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export VERSION_TAG=$(cat releasing/version/VERSION)
        echo ${VERSION_TAG}
        docker tag jupyter-tensorflow-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-full:${VERSION_TAG}
        docker tag jupyter-tensorflow-cuda-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-cuda-full:${VERSION_TAG}
