name: Build & Publish Jupyter Pytorch Full Notebook Server Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-pytorch-full/**
      - components/example-notebook-servers/jupyter-pytorch/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  DOCKER_USER: apoger
  REGISTRY: apoger

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Notebook Server images
      run: |
        export TAG=$(shell git describe --tags --always --dirty)
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full TAG=${TAG}
        make docker-build-cuda -C jupyter-pytorch-full TAG=${TAG}
        docker tag jupyter-pytorch-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker tag jupyter-pytorch-cuda-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}

    - name: Build and push latest Notebook Server images
      if: github.ref == 'refs/heads/master'
      run: |  
        export TAG=latest
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full TAG=${TAG}
        make docker-build-cuda -C jupyter-pytorch-full TAG=${TAG}
        docker tag jupyter-pytorch-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker tag jupyter-pytorch-cuda-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}

    - name: Build and push Notebook Server images on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-pytorch-full TAG=${TAG}
        make docker-build-cuda -C jupyter-pytorch-full TAG=${TAG}
        docker tag jupyter-pytorch-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-full:${TAG}
        docker tag jupyter-pytorch-cuda-full:${TAG} ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}
        docker push ${{env.REGISTRY}}/jupyter-pytorch-cuda-full:${TAG}
