name: Build Codeserver Python Notebook Server Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/codeserver-python/**
      - components/example-notebook-servers/codeserver/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  TAG: top-level-latest
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build & TAG Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build -C codeserver-python TAG=${{env.TAG}}
    
    - name: TAG Notebook Server images
      run: |
        docker tag codeserver-python:${{env.TAG}} ${{env.REGISTRY}}/codeserver-python:${{env.TAG}}
        kind load docker-image ${{env.REGISTRY}}/codeserver-python:${{env.TAG}}

    - name: TAG Notebook Server images on Version change
      run: |
        export VERSION_TAG=$(cat releasing/version/VERSION)
        echo ${VERSION_TAG}
        docker tag codeserver-python:${{env.TAG}} ${{env.REGISTRY}}/codeserver-python:${VERSION_TAG}
        kind load docker-image ${{env.REGISTRY}}/codeserver-python:${VERSION_TAG}
        docker images

