name: Build & Publish CentralDashboard-Angular Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/centraldashboard-angular
  TAG: $(git describe --tags --always --dirty)

jobs:
  push_to_registry:
    name: TEST
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: test
      run: |
        VERSION_TAG=$(cat releasing/version/VERSION)
        echo ${VERSION_TAG}
