name: Build & Publish CentralDashboard Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
    - components/example-notebook-servers/codeserver-python/**
    - components/example-notebook-servers/codeserver/**
    - components/example-notebook-servers/base/**
    - releasing/version/VERSION

env:
  TAG: test
  REGISTRY: apoger

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build -C codeserver-python
        docker tag codeserver-python:${TAG} ${{env.REGISTRY}}/codeserver-python:${TAG}
        docker push ${{env.REGISTRY}}/codeserver-python:${TAG}