name: Build VWA Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/volumes-web-app
  ARCH: linux/ppc64le,linux/amd64
  TAG: top-level-latest

jobs:
  push_to_registry:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi-arch docker image
      run: |
        cd  components/crud-web-apps/volumes
        make docker-build-multi-arch

    - name: Build multi-arch docker image on Version change
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd  components/crud-web-apps/volumes
        make docker-build-multi-arch 